POST http://localhost:3001/register/
Content-Type: application/json

{
  "username": "ABCD",
  "name": "ABCD",
  "password": "12345",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3001/login/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###

PUT http://localhost:3001/change-password/
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}


